services:
  - type: web
    name: hospital-portal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hospital_portal.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
