# Generated by Django 4.2.30 on 2026-07-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CARDIO', 'Cardiology'), ('PEDIA', 'Pediatrics'), ('ORTHO', 'Orthopedics'), ('NEURO', 'Neurology')], max_length=10)),
                ('specialization', models.CharField(max_length=150)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(help_text='Comma-separated days, e.g. Monday, Wednesday, Friday', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00 - 10:00', '09:00 AM - 10:00 AM'), ('10:00 - 11:00', '10:00 AM - 11:00 AM'), ('11:00 - 12:00', '11:00 AM - 12:00 PM'), ('12:00 - 13:00', '12:00 PM - 01:00 PM'), ('14:00 - 15:00', '02:00 PM - 03:00 PM'), ('15:00 - 16:00', '03:00 PM - 04:00 PM'), ('16:00 - 17:00', '04:00 PM - 05:00 PM')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'appointment_date', 'time_slot')},
            },
        ),
    ]
